version: '2.0'

volumes:
  data-web:

services:
  mongo:
    build:
      context: ..
      dockerfile: devops/dockerfile.mongo
    volumes:
      - /data/db:/data/db
  api:
    build:
      context: ..
      dockerfile: devops/dockerfile.api
    ports:
      - '5002'
    depends_on:
      - mongo
  nginx:
    build:
      context: ..
      dockerfile: devops/dockerfile.nginx
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
    depends_on:
      - api
