version: '3.0'

services:
  mongo:
    image: mongo
    volumes:
      - ${PWD}/data/db:/data/db
  api:
    build:
      context: ..
      dockerfile: devops/dockerfile.api
    ports:
      - '5003:5002'
    depends_on:
      - mongo
    environment:
      YOYO_JWT_SECRET: 'soooocoooool'
      YOYO_JWT_EXPIRES_IN: '10d'
      YOYO_ADMIN_USERNAME: 'YoYo'
      YOYO_ADMIN_PASSWORD: 'Happy_2014'
  nginx:
    build:
      context: ..
      dockerfile: devops/dockerfile.nginx
    ports:
      - '80:80'
    depends_on:
      - api
