version: '3.0'

volumes:
  dist:

services:
  mongo:
    image: mongo
    volumes:
      - /data/db:/data/db
  api:
    build:
      context: ..
      dockerfile: devops/dockerfile.api
    ports:
      - '5002:5002'
    depends_on:
      - mongo
  client:
    build:
      context: ..
      dockerfile: devops/dockerfile.client
    ports:
      - '9090:80'
    depends_on:
      - api
  admin:
    build:
      context: ..
      dockerfile: devops/dockerfile.admin
    ports:
      - '8080:80'
    depends_on:
      - api
  nginx:
    build:
      context: ..
      dockerfile: devops/dockerfile.nginx
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - dist:/data/dist/v0.1
    ports:
      - '80:80'
      - '443:443'
    depends_on:
      - client
      - admin
