version: '3.0'

services:
  mongo:
    image: mongo
    volumes:
      - /Users/mhuang/Codes/YoYo/devops/db:/data/db
  api:
    image: metrue/yoyo_api:latest
    build:
      context: ..
      dockerfile: devops/dockerfile.api
    ports:
      - '5002:5002'
    depends_on:
      - mongo
  nginx:
    build:
      context: ..
      dockerfile: devops/dockerfile.nginx
    ports:
      - '80:80'
    volumes:
      - /Users/mhuang/Codes/YoYo/devops/letsencrypt:/etc/letsencrypt
      - /Users/mhuang/Codes/YoYo/client/public/dist/index.js:/data//dist/v0.1/yoyo.js
    depends_on:
      - api
