version: '3.0'

services:
  mongo:
    image: mongo
    volumes:
      - ${PWD}/data/db:/data/db
  api:
    build:
      context: ../../
      dockerfile: devops/local/dockerfile.api
    ports:
      - '5002:5002'
    depends_on:
      - mongo
  client:
    build:
      context: ../../
      dockerfile: devops/local/dockerfile.client
    ports:
      - '9090:80'
    depends_on:
      - api
  admin:
    build:
      context: ../../
      dockerfile: devops/local/dockerfile.admin
    ports:
      - '8080:80'
    depends_on:
      - api
  nginx:
    build:
      context: ../../
      dockerfile: devops/local/dockerfile.nginx
    ports:
      - '80:80'
      - '443:443'
    depends_on:
      - client
      - admin
